### ISSUE TITLE
distributing libraries with dependencies

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#415] opened 2015-11-02 09:36 UTC
what is the best way to distribute dependencies with erlang.mk ? How to make sure that an application including your project will fetch all the dependencies needed by a library? I didn't find it a good way to do it from the doc yet.

**Comment by essen** [comment] 2015-11-02 22:08
Not sure what you mean?

Just setup the deps in your Makefile like:

dep_cowboy = git https://github.com/ninenines/cowboy 1.1.0

**Comment by benoitc** [comment] 2015-11-03 06:49
i meaan i have a lib with deps i want to ship. this lib will be included in projects on top. how to make sure that the projects will alsos get the dependencies without reading them in the project makefile?

**Comment by essen** [comment] 2015-11-03 09:01
I still don't know what you mean. Without reading them from the Makefile? Where would they find them?

Can you point me to an equivalent of what you want to do?

**Comment by benoitc** [comment] 2015-11-03 10:35
well. see i have a lib which have dependencies. How the dependencies  from
this library are discovered by  the application. Should I also provides a
makefile in the library? Or does it handle the rebar.config ? In that case
does it handle the rebar3 format for dependencies coming from hex?

**Comment by essen** [comment] 2015-11-03 11:05
Erlang.mk can compile rebar3, which uses hex deps, so I don't think you need to worry about anything.

Though for hackney there is an issue with one dep I believe, because its Makefile doesn't include it. Should be a ticket here.

But barring small issues with a limited number of projects, Erlang.mk detects rebar2 and 3 projects and builds them as intended.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by essen** [comment] 2015-11-11 11:06
Don't know if that answer was satisfying, closing for now. Reopen if needed. Thanks!

**Closed by essen** 2015-11-11 11:06 UTC
