### ISSUE TITLE
Jiffy doesn't compile with latest erlang.mk

### ISSUE THREAD

**Issue by elbrujohalcon** [ninenines/erlang.mk#267] opened 2015-06-06 22:32 UTC
I had an older version of erlang.mk on github.com/inaka/tirerl and everything was fine and shinny… :sunny: 
I run `make erlang-mk` and then, when I try to compile the project again…

```bash
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f c_src/Makefile.erlang.mk
cc -c -o c_src/decoder.o c_src/decoder.c -g -Wall  -O3 -fno-strict-aliasing -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
cc -c -o c_src/encoder.o c_src/encoder.c -g -Wall  -O3 -fno-strict-aliasing -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
cc -c -o c_src/jiffy.o c_src/jiffy.c -g -Wall  -O3 -fno-strict-aliasing -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
cc -c -o c_src/utf8.o c_src/utf8.c -g -Wall  -O3 -fno-strict-aliasing -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
cc -c -o c_src/util.o c_src/util.c -g -Wall  -O3 -fno-strict-aliasing -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/doubles.o c_src/doubles.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/bignum-dtoa.o c_src/double-conversion/bignum-dtoa.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/bignum.o c_src/double-conversion/bignum.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/cached-powers.o c_src/double-conversion/cached-powers.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/diy-fp.o c_src/double-conversion/diy-fp.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/double-conversion.o c_src/double-conversion/double-conversion.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/fast-dtoa.o c_src/double-conversion/fast-dtoa.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/fixed-dtoa.o c_src/double-conversion/fixed-dtoa.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
c++ -c -o c_src/double-conversion/strtod.o c_src/double-conversion/strtod.cc -g -Wall  -O3 -finline-functions -Wall -fPIC -I /usr/local/lib/erlang/erts-6.4.1/include -I /usr/local/lib/erlang/lib/erl_interface-3.7.20/include -fPIC
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
cc -o priv/jiffy.so c_src/decoder.o c_src/encoder.o c_src/jiffy.o c_src/utf8.o c_src/util.o c_src/doubles.o c_src/double-conversion/bignum-dtoa.o c_src/double-conversion/bignum.o c_src/double-conversion/cached-powers.o c_src/double-conversion/diy-fp.o c_src/double-conversion/double-conversion.o c_src/double-conversion/fast-dtoa.o c_src/double-conversion/fixed-dtoa.o c_src/double-conversion/strtod.o -lstdc++ -L /usr/local/lib/erlang/lib/erl_interface-3.7.20/lib -lerl_interface -lei   -shared
Undefined symbols for architecture x86_64:
  "_enif_alloc", referenced from:
      _dec_new in decoder.o
      _dec_push in decoder.o
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _load in jiffy.o
  "_enif_alloc_binary", referenced from:
      _enc_new in encoder.o
      _encode_iter in encoder.o
  "_enif_alloc_resource", referenced from:
      _dec_new in decoder.o
      _decode_init in decoder.o
      _enc_new in encoder.o
  "_enif_compare", referenced from:
      _decode_init in decoder.o
      _encode_init in encoder.o
      _encode_iter in encoder.o
      _get_bytes_per_iter in util.o
  "_enif_consume_timeslice", referenced from:
      _consume_timeslice in util.o
  "_enif_free", referenced from:
      _dec_destroy in decoder.o
      _dec_push in decoder.o
      _decode_iter in decoder.o
      _unload in jiffy.o
  "_enif_get_atom", referenced from:
      _enc_string in encoder.o
  "_enif_get_double", referenced from:
      _encode_iter in encoder.o
  "_enif_get_list_cell", referenced from:
      _make_object in decoder.o
      _make_array in decoder.o
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _encode_init in encoder.o
      _encode_iter in encoder.o
  "_enif_get_long", referenced from:
      _encode_iter in encoder.o
  "_enif_get_map_size", referenced from:
      _enc_map_to_ejson in encoder.o
  "_enif_get_resource", referenced from:
      _decode_iter in decoder.o
      _encode_iter in encoder.o
  "_enif_get_tuple", referenced from:
      _encode_iter in encoder.o
      _get_bytes_per_iter in util.o
  "_enif_get_uint", referenced from:
      _get_bytes_per_iter in util.o
  "_enif_inspect_binary", referenced from:
      _decode_iter in decoder.o
      _enc_string in encoder.o
  "_enif_is_atom", referenced from:
      _encode_iter in encoder.o
      _enc_string in encoder.o
  "_enif_is_binary", referenced from:
      _encode_iter in encoder.o
      _enc_string in encoder.o
  "_enif_is_empty_list", referenced from:
      _decode_iter in decoder.o
      _encode_iter in encoder.o
  "_enif_is_identical", referenced from:
      _encode_iter in encoder.o
  "_enif_is_list", referenced from:
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _encode_init in encoder.o
      _encode_iter in encoder.o
  "_enif_is_map", referenced from:
      _encode_iter in encoder.o
  "_enif_make_atom", referenced from:
      _make_atom in util.o
      _make_error in util.o
      _make_obj_error in util.o
  "_enif_make_badarg", referenced from:
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _encode_init in encoder.o
      _encode_iter in encoder.o
  "_enif_make_binary", referenced from:
      _enc_result in encoder.o
      _enc_done in encoder.o
      _encode_iter in encoder.o
  "_enif_make_double", referenced from:
      _dec_number in decoder.o
  "_enif_make_existing_atom", referenced from:
      _make_atom in util.o
      _make_error in util.o
      _make_obj_error in util.o
  "_enif_make_int", referenced from:
      _dec_error in decoder.o
      _decode_iter in decoder.o
  "_enif_make_list", referenced from:
      _make_empty_object in decoder.o
      _make_object in decoder.o
      _make_array in decoder.o
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _enc_map_to_ejson in encoder.o
      _encode_init in encoder.o
      ...
  "_enif_make_list_cell", referenced from:
      _make_object in decoder.o
      _make_array in decoder.o
      _decode_iter in decoder.o
      _enc_done in encoder.o
      _enc_map_to_ejson in encoder.o
      _encode_iter in encoder.o
  "_enif_make_long", referenced from:
      _dec_number in decoder.o
  "_enif_make_map_put", referenced from:
      _make_object in decoder.o
  "_enif_make_new_binary", referenced from:
      _dec_string in decoder.o
  "_enif_make_new_map", referenced from:
      _make_empty_object in decoder.o
      _make_object in decoder.o
      _decode_iter in decoder.o
  "_enif_make_resource", referenced from:
      _decode_init in decoder.o
      _encode_init in encoder.o
  "_enif_make_sub_binary", referenced from:
      _dec_string in decoder.o
      _dec_number in decoder.o
  "_enif_make_tuple", referenced from:
      _dec_error in decoder.o
      _dec_number in decoder.o
      _make_empty_object in decoder.o
      _make_object in decoder.o
      _decode_iter in decoder.o
      _enc_map_to_ejson in encoder.o
      _encode_iter in encoder.o
      ...
  "_enif_map_iterator_create", referenced from:
      _enc_map_to_ejson in encoder.o
  "_enif_map_iterator_get_pair", referenced from:
      _enc_map_to_ejson in encoder.o
  "_enif_map_iterator_next", referenced from:
      _enc_map_to_ejson in encoder.o
  "_enif_open_resource_type", referenced from:
      _load in jiffy.o
  "_enif_priv_data", referenced from:
      _dec_new in decoder.o
      _decode_init in decoder.o
      _decode_iter in decoder.o
      _enc_new in encoder.o
      _encode_init in encoder.o
      _encode_iter in encoder.o
      _get_bytes_per_iter in util.o
      ...
  "_enif_realloc_binary", referenced from:
      _enc_result in encoder.o
      _enc_done in encoder.o
      _encode_iter in encoder.o
      _enc_string in encoder.o
  "_enif_release_binary", referenced from:
      _enc_destroy in encoder.o
  "_enif_release_resource", referenced from:
      _decode_init in decoder.o
      _enc_new in encoder.o
      _encode_init in encoder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [priv/jiffy.so] Error 1
make[1]: *** [pre-app] Error 2
make: *** [deps] Error 2
```

This is a Mac OSX 10.10.4 (if that's somehow important)

**Comment by essen** [comment] 2015-06-07 06:50
Yeah I don't have an OSX test environment setup yet so NIFs might be buggy on it still. I'll get back to you later today.

**Comment by essen** [comment] 2015-06-07 16:47
It took me almost a whole day to install OSX, but I can reproduce so I will fix it in the evening or tomorrow. Have to pack my bags so we'll see how that goes.

**Comment by essen** [comment] 2015-06-07 17:40
So the issue is that it's missing "-flat_namespace -undefined suppress" when patching rebar projects. I will have a fix after food. Will also remove that annoying warning.

**Comment by essen** [comment] 2015-06-07 19:32
Should be fixed now. The annoying warning about the option is still there, I am keeping it for later in the following ticket: #268

Enjoy!

**Closed by essen** 2015-06-07 19:32 UTC

**Comment by elbrujohalcon** [comment] 2015-06-08 01:53
It **does work** :+1:
