### ISSUE TITLE
"make dialyze" with non- Erlang deps

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#439] opened 2015-11-29 20:07 UTC
I have an erlang.mk project with a Golang github dependency; the project links to the Golang code via a port

If I try and do a standard 'make' I get the following

Failed to solve release:
 Dependency XXX is specified as a dependency but is not reachable by the system.

So I add a manually- configured '.app.src' file with the Golang dependency missing and 'make' works fine again

However the same trick doesn't seem to work for 'make dialyze'; the system produces the same error as above

Is there a way to get 'make dialyze' to work with (ie ignore) non- Erlang projects ?

Thx

**Comment by essen** [comment] 2015-11-29 21:15
The Golang dependency should be set as BUILD_DEPS and not as DEPS.

**Comment by essen** [comment] 2015-11-29 21:15
I'll check, wasn't aware this was an issue.

**Comment by essen** [comment] 2015-11-29 21:25
Though a quick look tells me using BUILD_DEPS instead of DEPS will also fix Dialyzer for you.

**Comment by essen** [comment] 2015-11-29 23:27
Closing as I believe this is not a bug but expected behavior. Non-Erlang dependencies should be specified in BUILD_DEPS and not in DEPS, otherwise they get included in everything Erlang related, including building a release or running Dialyzer. Thanks!

**Closed by essen** 2015-11-29 23:27 UTC

**Comment by jhw** [comment] 2015-11-30 05:55
Thank you
