### ISSUE TITLE
Issue with erlydtl.app.src.script

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#374] opened 2015-09-26 20:18 UTC
Hi,
I found an issue using erlydtl as dependency with 18.1 release when compiling with erlang.mk.
erlydtl does not need merl module anymore because now integrated in erlang syntax_tools.
This is achieved with erlydtl/src/erlydtl.app.src.script and works nice when compiling deps/erlydtl manually with rebar, but does not work when compiling with erlang.mk upper project. By not working, I mean it is compiling, but release fails due to module merl conflict .
See also original erlydtl issue : 
https://github.com/erlydtl/erlydtl/issues/221

**Comment by essen** [comment] 2015-09-26 20:30
As a quick workaround, add this to your Makefile:

IGNORE_DEPS = merl

I will see when I can about the rebar.config.script issue.

**Comment by crownedgrouse** [comment] 2015-09-26 20:34
Thanx, I will try. Maybe rebar should be used when a rebar.config.script is found ?

**Comment by essen** [comment] 2015-09-26 20:35
Rebar isn't compatible with Erlang.mk, unfortunately. We do use Rebar to patch Rebar out, and it works very well in most cases. I'll just have to check what I forgot to support.

**Comment by crownedgrouse** [comment] 2015-09-26 20:40
the workaround does not work, do not see why at the moment. I will compile erlydtl with rebar and remind not distclean for the moment.

**Comment by essen** [comment] 2015-09-26 20:41
Make sure to update Erlang.mk: make erlang-mk

**Comment by crownedgrouse** [comment] 2015-09-26 20:43
I did it, but no way. I will wait for a fix . I m not blocked.

**Comment by essen** [comment] 2015-09-26 20:45
Yeah but if you have a problem with IGNORE_DEPS I would like to be sure. I just fixed it this week. You need to "rm -rf deps/erlydtl deps/merl", then try to make again. It's not supposed to fetch merl at all.

**Comment by crownedgrouse** [comment] 2015-09-26 20:49
It does not change the problem, unfortunately. merl is not anymore in deps/ but my release crash anyway, while running nice when using rebar in subfolder.

**Comment by crownedgrouse** [comment] 2015-09-26 20:57
https://github.com/erlydtl/erlydtl/commit/b992c452c1d61adbc871d6d7df8a3c9236bf7444

see src/erlydtl_beam_compiler.erl  . A define include either merl or syntax_tool merl .hrl file. it may explain why my release crash  with {'EXIT',{undef,[{compile,forms,[[{attribute,485,module,template_name}

**Comment by crownedgrouse** [comment] 2015-09-26 20:59
rebar.config.script  declare  {erl_opts, [{d, 'MERL_DEP'}]}]);

**Comment by essen** [comment] 2015-09-26 21:01
It defines it if you need merl, and it's not the issue. The rebar.config.script works fine.

The issue is that apparently erlydtl.app.src.script is a thing. And that's not something I anticipated. I'll have to add support for it.

**Comment by essen** [comment] 2015-09-26 21:02
And I guess I must be tired because you said that's the problem all along. Cheers.

**Comment by crownedgrouse** [comment] 2015-09-26 21:04
have a rest , dude.

**Comment by Andy-Richards** [comment] 2015-11-13 09:55
+1 this ones catching me out too using erlydtl & erlang 18.1

**Comment by essen** [comment] 2015-12-04 15:49
I got a fix. Unfortunately it will take me a few hours to confirm it doesn't break something else (have to test against all packages). You can however apply the patch directly if you want:

``` patch
diff --git a/core/deps.mk b/core/deps.mk
index 656ebcc..f2b9760 100644
--- a/core/deps.mk
+++ b/core/deps.mk
@@ -107,6 +107,9 @@ define dep_autopatch
 endef
 
 define dep_autopatch2
+   if [ -f $(DEPS_DIR)/$1/src/$1.app.src.script ]; then \
+       $(call erlang,$(call dep_autopatch_appsrc_script.erl,$(1))); \
+   fi; \
    $(call erlang,$(call dep_autopatch_appsrc.erl,$(1))); \
    if [ -f $(DEPS_DIR)/$(1)/rebar.config -o -f $(DEPS_DIR)/$(1)/rebar.config.script ]; then \
        $(call dep_autopatch_fetch_rebar); \
@@ -480,6 +483,15 @@ define dep_autopatch_app.erl
    halt()
 endef
 
+define dep_autopatch_appsrc_script.erl
+   AppSrc = "$(call core_native_path,$(DEPS_DIR)/$1/src/$1.app.src)",
+   AppSrcScript = AppSrc ++ ".script",
+   Bindings = erl_eval:new_bindings(),
+   {ok, Conf} = file:script(AppSrcScript, Bindings),
+   ok = file:write_file(AppSrc, io_lib:format("~p.~n", [Conf])),
+   halt()
+endef
+
 define dep_autopatch_appsrc.erl
    AppSrcOut = "$(call core_native_path,$(DEPS_DIR)/$1/src/$1.app.src)",
    AppSrcIn = case filelib:is_regular(AppSrcOut) of false -> "$(call core_native_path,$(DEPS_DIR)/$1/ebin/$1.app)";
```

**Comment by essen** [comment] 2015-12-04 17:43
Looks like it doesn't break anything. In fact, one more package started to work, though that's probably unrelated. I will push in a minute!

**Comment by essen** [comment] 2015-12-04 17:45
Done! Closing, thanks!

**Closed by essen** 2015-12-04 17:45 UTC
Labels: Packages

**Comment by crownedgrouse** [comment] 2015-12-04 21:05
thanks. Confirming it is working nice now.
