### ISSUE TITLE
Lexer file removed when running tests

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#710] opened 2017-07-08 22:06 UTC
Hi,
I did a make erlang-mk today, and see an issue I think I did not have before.

My project need a leex/yecc module.
xrl file is well compiled, and .erl created, and working fine.
but when running 'make all' , then 'make tests' fails.

```
$> make all
 XYRL   jason_lex.xrl jason_yec.yrl
Parsing file src/jason_lex.xrl, contained 17 rules.
NFA contains 78 states, DFA contains 46 states, minimised to 38 states.
Writing file src/jason_lex.erl, ok
 DEPEND jason.d
 ERLC   jason.erl jason_lex.erl jason_lib.erl jason_pp.erl jason_tests.erl jason_yec.erl
Old inliner: threshold=0 functions=[{yyaction_16,2},
                                    {yyaction_15,3},
                                    {yyaction_14,0},
                                    {yyaction_13,2},
                                    {yyaction_12,2},
                                    {yyaction_11,1},
                                    {yyaction_10,1},
                                    {yyaction_9,1},
                                    {yyaction_8,1},
                                    {yyaction_7,1},
                                    {yyaction_6,1},
                                    {yyaction_5,1},
                                    {yyaction_4,1},
                                    {yyaction_3,1},
                                    {yyaction_2,1},
                                    {yyaction_1,1},
                                    {yyaction_0,1}]
Old inliner: threshold=0 functions=[{yeccpars2_52_,1},
                                    {yeccpars2_51_,1},
                                    {yeccpars2_50_,1},
                                    {yeccpars2_49_,1},
                                    {yeccpars2_46_,1},
                                    {yeccpars2_44_,1},
                                    {yeccpars2_43_,1},
                                    {yeccpars2_42_,1},
                                    {yeccpars2_40_,1},
                                    {yeccpars2_39_,1},
                                    {yeccpars2_32_,1},
                                    {yeccpars2_30_,1},
                                    {yeccpars2_29_,1},
                                    {yeccpars2_27_,1},
                                    {yeccpars2_26_,1},
                                    {yeccpars2_23_,1},
                                    {yeccpars2_22_,1},
                                    {yeccpars2_20_,1},
                                    {yeccpars2_19_,1},
                                    {yeccpars2_18_,1},
                                    {yeccpars2_17_,1},
                                    {yeccpars2_15_,1},
                                    {yeccpars2_14_,1},
                                    {yeccpars2_13_,1},
                                    {yeccpars2_8_,1},
                                    {yeccpars2_6_,1}]
 APP    jason
eric@cameleon:~/git/jason$ ls -l src/jason_lex.erl
-rw-rw-r-- 1 eric eric 28991 juil.  8 23:58 src/jason_lex.erl
```
Lexer file is well generated.

But when wanting to run eunit tests, erlang.mk complain that the lexer file is missing...
while I did not do a 'make clean' . And the file is really missing

```
eric@cameleon:~/git/jason$ make tests
 GEN    clean-app
 GEN    coverdata-clean
 ERLC   jason.erl jason_lib.erl jason_pp.erl jason_tests.erl jason_lex.erl jason_yec.erl
src/jason_lex.erl: no such file or directory
erlang.mk:5039 : la recette pour la cible « ebin/jason.app » a échouée
make[1]: *** [ebin/jason.app] Erreur 1
erlang.mk:5149 : la recette pour la cible « test-build » a échouée
make: *** [test-build] Erreur 2
```

Actually I cannot run my tests !

**Comment by essen** [comment] 2017-07-08 22:14
Removal is normal, going from normal to test triggers a recompile. But I guess it didn't get recompiled.

Try "make clean ; touch ebin/test ; make tests" for now, I think that should fix it, and I'll try to see what the problem is later.

**Comment by crownedgrouse** [comment] 2017-07-08 22:16
yes works !

**Comment by crownedgrouse** [comment] 2017-08-16 10:03
for your information, running 'make tests' twice  let the second try be ok.
I tried to figure out where was the issue, but code became harder to understand in time. Did not reach to fix and propose a PR, sorry.

**Comment by essen** [comment] 2018-11-26 14:22
This should be fixed in the current master.

**Closed by essen** 2018-11-26 14:22 UTC
