### ISSUE TITLE
First try with erl 25.0 rc1

### ISSUE THREAD

**Issue by comptekki** [ninenines/erlang.mk#945] opened 2022-02-17 15:59 UTC
FYI with erl 25 rc1, I thought I'd try it and when running make to create a release, I get this error:

escript: exception error: undefined function relx:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [erlang.mk:7506: relx-rel] Error 127

**Comment by essen** [comment] 2022-02-17 17:08
I will have to rebuild a relx binary probably since it dropped support for 20 beam files.

**Comment by crownedgrouse** [comment] 2022-04-10 10:38
Having same issue with 25-rc2 .  Any update on this issue ?

```
escript: exception error: undefined function relx:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
erlang.mk:7505: recipe for target 'relx-rel' failed
```

**Comment by essen** [comment] 2022-04-10 10:55
Forgot about it. Will do that on Monday.

**Comment by essen** [comment] 2022-04-12 12:21
I'm afraid it looks a bit more difficult than just recompiling against 22+. The release generated by Relx no longer contains a RELEASES file which is necessary for some features to work (such as release upgrades). I can create an empty RELEASES file and this will let most use of releases work but NOT release upgrades. For that upgrading Relx will certainly be necessary, and that implies switching from escript to using it as a library.

So for the time being I will push the update that makes it work in all cases except release upgrades, but then I will have to find time to do a proper move to Relx 4. This is going to be a breaking change (although we can support both modes for the time being).

**Comment by essen** [comment] 2022-04-12 12:27
I have pushed the temporary commit.

**Comment by comptekki** [comment] 2022-04-15 18:36
I added the updated erlang.mk, but when I gmake on freebsd is says:

touch: _rel/projname_release/releases/RELEASES: No such file or directory
gmake: *** [erlang.mk:7507: relx-rel] Error 1

but if I do:

mkdir _rel/projname_release/releases

touch _rel/projname_release/releases/RELEASES

then run gmake again, it works.

I'm not sure why there is a projname_release.  I thank it should just be projname in the path.

**Comment by essen** [comment] 2022-04-18 15:44
I probably used the wrong variable. I'll take a look when I can.

**Comment by essen** [comment] 2022-04-26 10:53
Hm I will change it to use `$(PROJECT)` but this is not the right fix. I have to upgrade Relx soon.

**Comment by essen** [comment] 2022-04-26 10:56
Actually that's probably because you have a relx.config that changes the default release name. So it's a bit more complicated. I will just have to upgrade Relx.

**Comment by crownedgrouse** [comment] 2022-04-26 10:56
Still in rc2, no hurry.
But this must be fixed for 25 announcement.

**Comment by essen** [comment] 2022-04-26 11:00
Well rc3 is out so now is the time really.

**Comment by essen** [comment] 2022-04-26 12:20
I will have to remove a few things including `RELX_OPTS`, at least initially. It would be helpful if I could know which relx.config file and RELX_* configuration everyone is using.

**Comment by essen** [comment] 2022-04-26 14:55
I am making it similar to proper, which means relx will need to be added to REL_DEPS (or other relevant DEPS) in order to run.

**Comment by essen** [comment] 2022-04-27 14:49
Another heads up: these options will need to be set explicitly since it seems like the defaults have changed:

```
{dev_mode, false}.
{include_erts, true}.
```

**Comment by essen** [comment] 2022-04-27 15:04
Please try the `relx4` branch: https://github.com/ninenines/erlang.mk/tree/relx4

Note that it currently requires a custom relx if you are using simple integers for release versions. Also make note of the earlier comments.

**Comment by essen** [comment] 2022-04-27 15:25
I have opened https://github.com/erlware/relx/pull/911 to get the fix in the main Relx repository.

**Comment by comptekki** [comment] 2022-04-27 17:50
This is what I use for relx.config:

{release, {esysman, "1.20"}, [esysman]}.
{extended_start_script, true}.
{vm_args, "./config/vm.args"}.

**Comment by essen** [comment] 2022-04-28 14:48
Tests are now green on the branch (no changes to release code since yesterday) so it's just a matter of feedback or OTP 25 getting released. I will try on my own projects as well, I got a bunch in Cowboy and Ranch that can exercise these changes.

**Comment by essen** [comment] 2022-04-29 11:33
Windows now works but it required another relx patch. The relevant PR is https://github.com/erlware/relx/pull/914

**Comment by essen** [comment] 2022-04-29 14:35
Relevant problem if using OTP-25.0-rc2: https://github.com/erlang/otp/issues/5826

**Comment by crownedgrouse** [comment] 2022-05-07 12:24
Works for me now, thanks

**Comment by comptekki** [comment] 2022-05-11 19:14
In https://github.com/ninenines/erlang.mk/commit/aa0053cc593a70630db1f893707cfbb1ae6934b9 is there a reason you did this:

$(verbose) touch $(RELX_OUTPUT_DIR)/$(PROJECT)_release/releases/RELEASES

and not this:

$(verbose) touch $(RELX_OUTPUT_DIR)/$(PROJECT)/releases/RELEASES

When I take out the _releases, it works fine for me.

**Comment by essen** [comment] 2022-05-11 21:12
Neither are correct, the release name is provided in relx.config and is not dependent on `$(PROJECT)`. The one with `_release` is simply the default.

**Comment by comptekki** [comment] 2022-05-13 13:19
That line is on line 49 here:

https://github.com/ninenines/erlang.mk/blob/master/plugins/relx.mk

$(PROJECT)_release

should jsut be

$(PROJECT)

**Comment by essen** [comment] 2022-05-13 16:29
It is correct for the default as I've said, see https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L95

The real fix is in the `relx4` branch. Please try it and report feedback on that instead, as the `touch` workaround will be removed when that branch is merged.

**Comment by essen** [comment] 2022-05-19 07:14
I will merge the relx changes today. I will also investigate a potential issue with xref.

**Comment by essen** [comment] 2022-05-20 08:50
Merged! Thanks. I will investigate xref now.

**Closed by essen** 2022-05-20 08:50 UTC

**Comment by comptekki** [comment] 2022-05-20 19:18
Just an FYI: I just installed erlang 25, git cloned your erlang.mk project and ran make on it and put the erlang.mk in my project and all works with no error.  Thanks!

**Comment by comptekki** [comment] 2022-05-20 20:40
Hmm.  Maybe I'll need to redo how my project is set up.  I noticed now that "make distclean" does not remove _rel nor does "make" create a new _rel folder.  Any tips what direction I need to go for this?  Thanks

**Comment by comptekki** [comment] 2022-05-20 20:44
I probably just need to implement what you have in your comments about the braking changes.

**Comment by comptekki** [comment] 2022-05-20 22:21
This is what my make file looks like:

PROJECT = esysman

DEPS = cowboy epgsql
REL_DEPS = relx
dep_cowboy = git https://github.com/ninenines/cowboy 2.9.0
dep_epgsql = git https://github.com/wg/epgsql.git master
dep_relx = git https://github.com/erlware/relx master

include erlang.mk
include extra.mk

I get this now when running make:
...
DEPEND relx.d
 ERLC   relx.erl rlx_app_info.erl rlx_assemble.erl rlx_config.erl rlx_file_utils.erl rlx_log.erl rlx_overlay.erl rlx_release.erl rlx_relup.erl rlx_resolve.erl rlx_state.erl rlx_string.erl rlx_tar.erl rlx_util.erl
 APP    relx.app.src
make[1]: Leaving directory '/path/esysman/deps/relx'
erl +A1 -noinput -boot no_dot_erlang -pa ebin/ -pz /path/esysman/.erlang.mk/rebar/ebin -eval "       {ok, Config} = file:consult(\"/path/esysman/relx.config\"),      {release, {Name, Vsn0}, _} = lists:keyfind(release, 1, Config), Vsn = case Vsn0 of              {cmd, Cmd} -> os:cmd(Cmd);              semver -> \"\";         {semver, _} -> \"\";                VsnStr -> Vsn0  end,    {ok, _} = relx:build_release(#{name => Name, vsn => Vsn}, Config),      halt(0)." -- erlang.mk
Solving Release esysman-1.20{"init terminating in do_boot",{{error,{rlx_resolve,{app_not_found,esysman,undefined}}},[{rlx_resolve,subset,7,[{file,"src/rlx_resolve.erl"},{line,72}]},{rlx_resolve,'-fold_apps/7-fun-0-',7,[{file,"src/rlx_resolve.erl"},{line,99}]},{lists,foldl,3,[{file,"lists.erl"},{line,1350}]},{rlx_resolve,subset,5,[{file,"src/rlx_resolve.erl"},{line,54}]},{rlx_resolve,solve_release,2,[{file,"src/rlx_resolve.erl"},{line,48}]},{relx,build_release_,3,[{file,"src/relx.erl"},{line,170}]},{relx,build_release,3,[{file,"src/relx.erl"},{line,87}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]}]}}
init terminating in do_boot ({{error,{rlx_resolve,{app_not_found,esysman,undefined}}},[{rlx_resolve,subset,7,[{_},{_}]},{rlx_resolve,-fold_apps/7-fun-0-,7,[{_},{_}]},{lists,foldl,3,[{_},{_}]},{rlx_resolve,subset,5,[{_},{_}]},{rlx_resolve,solve_release,2,[{_},{_}]},{relx,build_release_,3,[{_},{_}]},{relx,build_release,3,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
make: *** [erlang.mk:7537: relx-rel] Error 1

**Comment by essen** [comment] 2022-05-21 07:05
Should have said BUILD_DEPS by the way. You probably don't want it included in the release.

Also please remove the dep_relx line and use the one defined by erlang.mk for now as it contains a fix that upstream relx hasn't merged yet. You might need to `make distclean` as well. If that fails please provide a test repository that I can use to reproduce.

**Comment by essen** [comment] 2022-05-27 10:31
Note that relx will be added automatically when creating a new project as of a few days ago.
