### ISSUE TITLE
`make -C apps/foo eunit` (multi-app repo) can't find include files

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#790] opened 2018-06-05 08:16 UTC
I've got `apps/test_helpers` and `apps/foo`. The unit tests for `foo` have `-include_lib("test_helpers/include/test_helpers.hrl").`.

When I run `make eunit` at the top level, everything's fine.

When I attempt to run the unit tests for a specific application (`make -C apps/foo eunit`, per the documentation), the `GEN test-dir` step fails with `can't find include lib "test_helpers/include/test_helpers.hrl"`.

**Comment by essen** [comment] 2018-06-05 08:27
Is this with the most recent Erlang.mk? I merged a PR not so long ago that fixed a bunch of multi-app issues with include files.

**Comment by rlipscombe** [comment] 2018-06-05 08:27
Lemme check; wait one.

**Comment by rlipscombe** [comment] 2018-06-05 08:29
Still broken with latest... :-(

**Comment by essen** [comment] 2018-06-05 08:32
Is the other app listed as a LOCAL_DEPS? Maybe that's all that's missing. We don't have a LOCAL_TEST_DEPS though but I think someone mentioned we should.

If not, could you add a test similar to https://github.com/ninenines/erlang.mk/blob/master/test/core_deps.mk#L260 that reproduces your issue?

**Comment by rlipscombe** [comment] 2018-06-05 08:34
Yeah, that someone was me :)

That issue explains why LOCAL_DEPS won't work for us in this case...

**Comment by rlipscombe** [comment] 2018-06-05 08:34
I'm working on a MVCE at the moment.

**Comment by rlipscombe** [comment] 2018-06-05 08:45
Here's what I've got so far: https://github.com/rlipscombe/erlang-mk-eunit-bug

**Comment by essen** [comment] 2018-06-05 08:48
Oh but that one's normal I think. Your helpers application is not an Erlang application and therefore include_lib is not supposed to work:

``` bash
ERL_LIBS=.. erlc test/test_foo.erl
```

**Comment by rlipscombe** [comment] 2018-06-05 08:51
Hmm...

```
$ ERL_LIBS=.. erlc test/test_foo.erl 
$ 
```

**Comment by essen** [comment] 2018-06-05 08:52
From apps/foo?

**Comment by rlipscombe** [comment] 2018-06-05 08:52
Yep.

**Comment by rlipscombe** [comment] 2018-06-05 08:54
> Your helpers application is not an Erlang application

Explain...?

If you mean that it's missing a `.app` (or `.app.src`) file, then I'm confused; `make -f erlang.mk new-app in=bar` doesn't create one; I assumed the default behaviour was sufficient.

**Comment by essen** [comment] 2018-06-05 09:01
Sorry for the noise I completely missed the include erlang.mk somehow and since you had no .erl file in helpers it didn't build anything (and has no .app file).

But that's not the issue.

I can't look further at the moment. It would help if you made this a test instead of a repo.

**Comment by rlipscombe** [comment] 2018-06-05 11:00
https://github.com/ninenines/erlang.mk/pull/791

**Comment by essen** [comment] 2018-11-23 15:35
Nevermind that's not enough for some other cases.

**Comment by essen** [comment] 2018-11-23 15:45
OK moving toward adding a variable that will be used by apps to determine where the top-level directory is and as a result whether they are apps.

**Comment by essen** [comment] 2018-11-23 17:13
OK this is fixed on my local copy, push soon.

**Comment by essen** [comment] 2018-11-23 17:14
For reference all I did was add this to the bootstrapped apps Makefile:

``` erlang
APPS_DIR := ..
DEPS_DIR := $(call core_relpath,$(DEPS_DIR),$(APPS_DIR)/app)
```

Plus a little more you shouldn't need.

**Closed by essen** 2018-11-23 17:13 UTC
