### ISSUE TITLE
env.src file for generation of ebin/.app file

### ISSUE THREAD

**Issue by lehoff** [ninenines/erlang.mk#366] opened 2015-09-18 18:48 UTC
The env part of a .app file is not really suited for translation into a Makefile syntax so the suggestion is to create a src/env.src file that holds the definition of the env key for the .app file.

A real-life example:
``` erlang
 {env, [
         %% Cluster name
         {cluster_name, "default"},

         %% Default location for ring, cluster and other data files
         {platform_data_dir, "data"},

         %% Default ring creation size.  Make sure it is a power of 2,
         %% e.g. 16, 32, 64, 128, 256, 512 etc
         {ring_creation_size, 64},

         %% Default gossip interval (milliseconds)
         {gossip_interval, 60000},

         %% Target N value
         {target_n_val, 4},

         %% Default claims functions
         {wants_claim_fun, {riak_core_claim, default_wants_claim}},
         {choose_claim_fun, {riak_core_claim, default_choose_claim}},

         %% Vnode inactivity timeout (how often to check if fallback vnodes
         %% should return their data) in ms.
         {vnode_inactivity_timeout, 60000},

         %% Number of VNodes allowed to do handoff concurrently.
         {handoff_concurrency, 2},

         %% Disable Nagle on HTTP sockets
         {disable_http_nagle, true},

         %% Handoff IP/port
         {handoff_port, 8099},
         {handoff_ip, "0.0.0.0"},

         %% Disterl buffer sizes in bytes.
         %% These sizes (3*128*1024 & 6*128*1024) were
         %% derived from a limited amount of testing in a
         %% 10GE environment, and may need tuning for your
         %% network and workload. In particular they're likely
         %% too small to be optimal for larger object sizes.
         {dist_send_buf_size, 393216},
         {dist_recv_buf_size, 786432},

     %% Exometer defaults
     {exometer_defaults,
      [
       {['_'], histogram, [{options,
                [{histogram_module, exometer_slot_slide},
                 {keep_high, 500}]}
                ]}
      ]}.
```

**Comment by essen** [comment] 2015-09-18 19:37
Yep, file should probably be this, minus the first line.

**Comment by lehoff** [comment] 2015-09-18 19:41
yeah, just the list would probably be a better choice

**Comment by essen** [comment] 2015-09-18 20:51
Having that kind of file would also make it easy to generate a global sys.config for all deps.

**Comment by essen** [comment] 2015-10-18 17:34
I think I will add two variables: PROJECT_ENV and PROJECT_ENV_FILE. We can use the same method as bootstrapping to handle multiline variables for PROJECT_ENV. And we can have PROJECT_ENV_FILE for people who want it separate. I'll have it done during the week.

**Comment by essen** [comment] 2016-10-19 16:25
FYI this is in! See #587 #588 and #589. Closing, thanks!

**Closed by essen** 2016-10-19 16:25 UTC
Labels: Feature request

**Comment by rossilazuardi** [comment] 2017-10-29 05:12
I know this is old threads, but i want to know, is this feature (PROJECT_ENV_FILE)  already implemented. Because i try add PROJECT_ENV_FILE= src/env.src on makefile, but it doesn't work.

**Comment by essen** [comment] 2017-10-29 08:31
We implemented `PROJECT_ENV` only. To use it with a file you can do:

```
PROJECT_ENV = $(file src/env.src)
```

Or to embed it directly in the Makefile:

```
define PROJECT_ENV
...
...
...
endef
```

**Comment by rossilazuardi** [comment] 2017-10-30 07:51
glad to know it.. i use the second approach.. because the first one seem's not working. it said 

```
erlang.mk:5149: *** Invalid file operation: src/env.src.  Stop.
erlang.mk:4940: recipe for target 'app' failed
make: *** [app] Error 2
```

**Comment by essen** [comment] 2017-10-30 09:27
My bad, it's `$(file < src/env.src)`.

**Comment by jimdigriz** [comment] 2018-04-13 12:46
Worth noting that `$(file < ...)` is a GNU make 4.2 feature, so you need to use something more like:
```
$(shell cat src/env.src)
```

Though now the problem is you probably also want to include in your `Makefile` (if maybe it should be in erlang.mk?):
```
.PHONY: ebin/$(PROJECT).app
```

**Comment by essen** [comment] 2018-04-13 12:51
Why the .PHONY?

It's a 4.2 feature but 4.2 has been available on many platforms for a while. If the Makefiles are not meant to be distributed publicly there's no problem in using these features.

**Comment by jimdigriz** [comment] 2018-04-13 12:57
The `.PHONY` is because editing `src/env.src` those changes do not make it to `ebin/$(PROJECT).app`, as `make` cannot tell the file needs rebuilding.

As for the version, sorry I am [stuck in the past](https://packages.debian.org/stretch/make), I suspect though others might be there with me too. :)

**Comment by nevar** [comment] 2018-04-13 12:58
@jimdigriz 
see my comment about `$(shell cat src/env.src)` https://github.com/ninenines/erlang.mk/pull/588#issuecomment-238146565 and final solution https://github.com/ninenines/erlang.mk/pull/588#issuecomment-240627360
And for regenerate .app you may append `ebin/$(PROJECT).app:: src/env.src` https://github.com/ninenines/erlang.mk/pull/588#issuecomment-238151077

**Comment by essen** [comment] 2018-04-13 12:59
Yeah Debian/Ubuntu and non-Homebrew OSX are in that boat.

Aaaaand @nevar gave the right answer about the rebuilding. Cheers.

**Comment by jimdigriz** [comment] 2018-04-13 13:06
Thanks both.

As its not in the docs for others who stumble here, add the following to your `Makefile`:
```
PROJECT_ENV_FILE = src/env.src
PROJECT_ENV = $(subst \n,$(newline),$(shell cat $(PROJECT_ENV_FILE) | sed 's/$$/\\n/'))
ebin/$(PROJECT).app:: $(PROJECT_ENV_FILE)
```

Now for your `src/env.src` file populate it with something like:
```
[
        {wibble, [
              {wobble, [{cheese,chips}]}
        ]},
        {jelly, [
              {tasty,jam}
        ]}
]
```

**Comment by essen** [comment] 2018-04-13 13:10
Feel free to send a patch to the docs near where PROJECT_ENV is defined. :-)

**Comment by jimdigriz** [comment] 2018-04-13 13:46
https://github.com/ninenines/erlang.mk/pull/766 but I'm not fixing that 'make asciidoc-guide' don't work (`make docs` works fine though):
```
alex@quatermain:/usr/src/erlang.mk$ make asciidoc
make: *** No rule to make target 'asciidoc'.  Stop.
alex@quatermain:/usr/src/erlang.mk$ make asciidoc
make: *** No rule to make target 'asciidoc'.  Stop.
alex@quatermain:/usr/src/erlang.mk$ make asciidoc-guide
make: *** No rule to make target 'asciidoc-guide'.  Stop.
alex@quatermain:/usr/src/erlang.mk$ make asciidoc-manual
make: *** No rule to make target 'asciidoc-manual'.  Stop.
alex@quatermain:/usr/src/erlang.mk$ make install-docs
make: *** No rule to make target 'install-docs'.  Stop.
```

**Comment by essen** [comment] 2018-04-13 13:49
Don't worry about it. Thanks!
